// src/ai/flows/natural-language-task-planning.ts
'use server';
/**
 * @fileOverview This file defines a Genkit flow for natural language task planning.
 *
 * It allows users to input a goal in natural language and have the app automatically
 * break it down into a list of actionable daily tasks using an LLM.
 *
 * @interface NaturalLanguageTaskPlanningInput - Defines the input schema for the flow.
 * @interface NaturalLanguageTaskPlanningOutput - Defines the output schema for the flow.
 * @function naturalLanguageTaskPlanning - The main function to trigger the task planning flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const NaturalLanguageTaskPlanningInputSchema = z.object({
  goal: z.string().describe('The overall goal to be achieved.'),
});

export type NaturalLanguageTaskPlanningInput = z.infer<typeof NaturalLanguageTaskPlanningInputSchema>;

const NaturalLanguageTaskPlanningOutputSchema = z.object({
  tasks: z.array(
    z.string().describe('A list of actionable daily tasks to achieve the goal.')
  ).describe('List of tasks generated by the AI.'),
});

export type NaturalLanguageTaskPlanningOutput = z.infer<typeof NaturalLanguageTaskPlanningOutputSchema>;

export async function naturalLanguageTaskPlanning(input: NaturalLanguageTaskPlanningInput): Promise<NaturalLanguageTaskPlanningOutput> {
  return naturalLanguageTaskPlanningFlow(input);
}

const naturalLanguageTaskPlanningPrompt = ai.definePrompt({
  name: 'naturalLanguageTaskPlanningPrompt',
  input: {schema: NaturalLanguageTaskPlanningInputSchema},
  output: {schema: NaturalLanguageTaskPlanningOutputSchema},
  prompt: `You are a personal assistant. Your job is to take a high-level goal and break it down into a list of actionable daily tasks.

Goal: {{{goal}}}

Tasks:`,
});

const naturalLanguageTaskPlanningFlow = ai.defineFlow(
  {
    name: 'naturalLanguageTaskPlanningFlow',
    inputSchema: NaturalLanguageTaskPlanningInputSchema,
    outputSchema: NaturalLanguageTaskPlanningOutputSchema,
  },
  async input => {
    const {output} = await naturalLanguageTaskPlanningPrompt(input);
    return output!;
  }
);
