
export const avatars = [
  { url: 'https://placehold.co/80x80.png', hint: '3d avatar man glasses' },
  { url: 'https://placehold.co/80x80.png', hint: '2d avatar woman smiling' },
  { url: 'https://placehold.co/80x80.png', hint: '3d avatar robot head' },
  { url: 'https://placehold.co/80x80.png', hint: 'pixel art wizard' },
  { url: 'https://placehold.co/80x80.png', hint: '2d avatar man beard' },
  { url: 'https://placehold.co/80x80.png', hint: '3d avatar woman headphones' },
  { url: 'https://placehold.co/80x80.png', hint: '2d avatar cat suit' },
  { url: 'https://placehold.co/80x80.png', hint: '3d character astronaut' },
  { url: 'https://placehold.co/80x80.png', hint: 'pixel art ninja' },
  { url: 'https://placehold.co/80x80.png', hint: '2d avatar girl pink hair' },
  { url: 'https://placehold.co/80x80.png', hint: '3d character fox' },
  { url: 'https://placehold.co/80x80.png', hint: '2d avatar man hoodie' },
  { url: 'https://placehold.co/80x80.png', hint: '3d avatar monster cute' },
  { url: 'https://placehold.co/80x80.png', hint: 'pixel art knight' },
  { url: 'https://placehold.co/80x80.png', hint: '2d avatar woman glasses' },
  { url: 'https://placehold.co/80x80.png', hint: '3d character panda suit' },
  { url: 'https://placehold.co/80x80.png', hint: '2d avatar man suit' },
  { url: 'https://placehold.co/80x80.png', hint: '3d avatar woman curly hair' },
  { url: 'https://placehold.co/80x80.png', hint: 'pixel art alien' },
  { url: 'https://placehold.co/80x80.png', hint: '2d avatar dog astronaut' },
];
